
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";

const jetBrains_Mono = JetBrains_Mono({
  weight: ["100", '200', '300', '400', '500', '600', '700', '800'],
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${jetBrains_Mono.className}`}>
        <Providers>
         <div className="px-2 md:px-4 md:py-20 lg:py-24 max-w-7xl mx-auto ">
           {children}
         </div>
        </Providers>
      </body>
    </html>
  );
}
