import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const jetBrains_Mono = JetBrains_Mono({
  weight: ["100", '200', '300', '400', '500', '600', '700', '800'],
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${jetBrains_Mono.className}`}>
        {/* Navbar section */}
        <Navbar />
        {children}
        {/* Footer section */}
      </body>
    </html>
  );
}
